server.port=9081
# Resource URL, for example https://data.cityofnewyork.us/resource/5uac-w243.json
socrata.url=https://data.cityofnewyork.us/resource/5uac-w243.json
# API Token. Create a Socrata account and create an API Token. Paste it here
socrata.api.token=
